favicon: https://cgabc.xyz/img/CGABC/icon/favicon.ico # /favicon.ico
banner: /images/webstack_banner_cn.png

logo:
  expanded: /img/favicon_800x600_inv.png # /images/logo@2x.png
  collapsed: https://cgabc.xyz/img/CGABC/icon/favicon.ico 
  dark: https://cgabc.xyz/img/favicon_800x600.png # /images/logo_dark@2x.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: true
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(https://www.baidu.com/favicon.ico)
  hotStatus: true
  data:
    - name: 百度
      img: url(https://www.baidu.com/favicon.ico)
      url: https://www.baidu.com/s?wd=
    - name: 谷歌
      img: url(https://www.google.com/favicon.ico)
      url: https://www.google.com/search?q=

githubCorner: '<a href="https://github.com/cggos/webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: false
menu:
  - name: 控制面板
    icon: fas fa-tools
    config: ctrlPanel
  - name: 网络调试 
    icon: fas fa-tools
    config: networkTools
  - name: 网站建设 
    icon: fas fa-tools
    config: websiteTools
  - name: 多媒体
    icon: far fa-star
    submenu:
      - name: 图床 (Image Hosting)
        icon: far fa-star
        config: imageHosting
  - name: 友链
    icon: far fa-star
    config: navLinks


  # - name: 
  #   url: 
  #   img: 
  #   description: 

ctrlPanel:
  - name: Op Router
    url: http://192.168.2.1
    img: https://openwrt.org/_media/favicon.ico
    description: Op Router (local)
  - name: ASUS Router (AP)
    url: http://192.168.2.100
    img: https://i.imgur.com/DLL6DwDt.png
    description: ASUS Router RT-AX56U V2 (local)
  - name: CG-NAS
    url: https://192.168.2.200:5001/
    img: https://i.imgur.com/TlIcFVXt.png
    description: CG-NAS (local)
  - name: CG-NAS
    url: https://cgabc.i234.me:5001/
    img: https://i.imgur.com/TlIcFVXt.png
    description: CG-NAS
  - name: CG-Alist
    url: http://192.168.2.200:5244
    img: https://cdn.jsdelivr.net/gh/alist-org/logo@main/logo.svg
    description: CG-Alist (local)
  - name: Calibre-Web
    url: http://192.168.2.200:8083
    img: https://calibre-ebook.com/favicon.png
    description: Calibre-Web (local)
  - name: Plex Media Server
    url: http://192.168.2.200:32400
    img: https://app.plex.tv/auth/favicon.ico
    description: Plex Media Server (local)

networkTools:
  - name: whoer
    url: https://whoer.net/
    img: https://whoer.net/favicon.png
    description: IP和DNS检查
  - name: IP Address
    url: https://www.ipaddress.com/
    img: https://s.ipaddress.com/icon/favicon-192.png
    description: The Best IP Address, Email and Networking Tools
  - name: IP.SB
    url: https://ip.sb/
    img: https://cdn.rsb.net/ip.sb/apple-touch-icon.png
    description: IP Address Lookup
  - name: ip.cn
    url: https://ip.cn/
    img: https://www.ip.cn/img/favicon.ico
    description: IP 地址查询 | 地理位置 | 手机归属地  | DNS查询
  - name: ip111
    url: http://ip111.cn/
    img: http://ip111.cn/favicon.ico
    description: 全方位查询您的IP地址
  - name: ipstack
    url: https://ipstack.com/
    img: https://ipstack.com/ipstack_images/ipstack_ico.ico
    description: Locate and identify website visitors by IP address
  - name: DNS服务器地址
    url: https://dns.supfree.net/
    img: https://www.supfree.net/favicon.ico
    description: DNS服务器地址

websiteTools:
  - name: W3Schools
    url: https://www.w3schools.com/
    img: https://www.w3schools.com/favicon.ico
    description: Online Web Tutorials
  - name: 站长之家 
    url: https://www.chinaz.com/
    img: https://i.imgur.com/MjwtEX1t.png
    description: 站长资讯-我们致力于为中文网站提供动力 
  - name: 阿里云控制台
    url: https://home.console.aliyun.com/
    img: https://img.alicdn.com/tfs/TB1_ZXuNcfpK1RjSZFOXXa6nFXa-32-32.ico
    description: 阿里云控制台

imageHosting:
  - name: imgur
    url: https://imgur.com/
    img: https://s.imgur.com/images/favicon-32x32.png
    description: Find, rate and share the best memes and images
  - name: Font Awesome
    url: https://fontawesome.com/
    img: https://fontawesome.com/favicon.ico
    description: Font Awesome
  - name: iconfont
    url: https://www.iconfont.cn/
    img: https://img.alicdn.com/imgextra/i2/O1CN01ZyAlrn1MwaMhqz36G_!!6000000001499-73-tps-64-64.ico
    description: 阿里巴巴矢量图标库

navLinks:
  - name: CGABC
    url: https://cgabc.xyz
    img: /img/favicon_800x600.png
    description: CGABC
  - name: 大黄蜂
    url: https://maopai8.com/
    img: https://maopai8.com/assets/images/favicon.png
    description: 大黄蜂2.0导航网站

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站基于hexo主题<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a></p></blockquote>'
  webmaster:
    head: 关于站长
    name: Gavin Gao
    url: https://cgabc.xyz
    img: /images/logos/myblog.png
    description: CGABC
    html: '<br /><blockquote><p>本站是<a href="https://github.com/cggos">Gavin Gao</a>基于<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>主题搭建的。</p></blockquote>'

since: 2022

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
